GET http://localhost:3003/users

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Teste2",
    "email": "teste2@gmail.com",
    "password": "1234"
} 

###
GET http://localhost:3003/users/001 

###
GET http://localhost:3003/products

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Pera fone",
    "price": 2500,
    "imageUrl": "https://64.media.tumblr.com/27070187217c500ac60dd34204339e76/tumblr_inline_mgcuuxMcuG1r8bj4b.png"
}

###
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "001",
    "productId": "c296e8a0-cccb-11ec-aeb9-af058412284d"
}