### Criar Competição
POST http://localhost:3003/competicao/create 
Content-Type: application/json

{
    "competicao": "Sem metros rasos"
}

### Get competições
GET http://localhost:3003/competicao/get

### Inserir dados de um competidor
POST http://localhost:3003/competidor/insert/aafb9343-cfc1-4092-9278-715062a5f669
Content-Type: application/json

{
    "competicao": "Sem metros rasos", 
    "atleta": "Joao das Neves", 
    "tempo": 9.234, 
    "unidade": "s"
}


### Encerrar uma Competição
POST http://localhost:3003/competicao/encerrar
Content-Type: application/json

{
    "name": "100m Rasos"
}

### Resultada da competição
GET http://localhost:3003/competicao/result
Content-Type: application/json

{
    "competicao": "Sem metros rasos"
}